NetCoreBlogEntires/Areas/Admin/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreBlogEntires.Areas.Admin.Models
{
    public class PostViewModel
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string ShortContent { get; set; }

        public int CommentCount { get; set; }

        public string AuthorName { get; set; }

        public string CategoryName { get; set; }

        public DateTime PublishDate { get; set; }

        public bool IsActive { get; set; }


    }
}

NetCoreBlogEntires/Areas/Admin/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NetCoreBlogEntires.Areas.Admin.Models;
using NetCoreBlogEntires.Data.Repositories;
using NetCoreBlogEntires.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreBlogEntires.Areas.Admin.Controllers
{
    [Area("Admin")][Authorize]
    public class PostController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPostService _postService;
        private readonly IPostRepository _postRepository;


        private List<SelectListItem> CategoryDrp 
        {
           get
            {
                return _categoryRepository.List().OrderBy(x=> x.Name).Select(a => new SelectListItem
                {
                    Text = a.Name,
                    Value = a.Id
                }).ToList();
            }
        }

        public PostController(ICategoryRepository categoryRepository, IPostService postService, IPostRepository postRepository)
        {
            _categoryRepository = categoryRepository;
            _postService = postService;
            _postRepository = postRepository;
        }
        public IActionResult Index()
        {
            var model = _postRepository.List().Select(a=> new PostViewModel
            {
                IsActive = a.IsActive,
                Title = a.Title,
                Id = a.Id,
                CategoryName = a.Category.Name,
                AuthorName = a.AuthorName,
                CommentCount = a.Comments.Count(),
                PublishDate = a.PublishDate,
                ShortContent = a.ShortContent
            }
            ).ToList();

            return View(model);
        }


        public IActionResult IndexMvcGrid()
        {
            var model = _postRepository.List().Select(a => new PostViewModel
            {
                IsActive = a.IsActive,
                Title = a.Title,
                Id = a.Id,
                CategoryName = a.Category.Name,
                AuthorName = a.AuthorName,
                CommentCount = a.Comments.Count(),
                PublishDate = a.PublishDate,
                ShortContent = a.ShortContent
            }
             ).AsQueryable();

            return View(model);
        }


        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = CategoryDrp;

            return View();
        }

        [HttpPost]
        public IActionResult Create(PostInputModel model)
        {
            ViewBag.Categories = CategoryDrp;

            if(ModelState.IsValid)
            {
                _postService.Save(model);
                ViewBag.Message = "Makale Kayıt işlemi başarılıdır";
            }
          
            return View();
        }


        public IActionResult Detail(string id)
        {
            var post = _postRepository.Find(id);
         

            if(post != null)
            {

                var model = new PostDetailViewModel
                {
                    AuthorName = post.AuthorName,
                    CategoryName = post.Category.Name,
                    HtmlContent = post.Content,
                    PublishDate = post.PublishDate.ToShortDateString(),
                    Tags = post.Tags.Select(x => x.Name).ToList(),
                    Title = post.Title
                };

                return View(model);
            }


            return NotFound();
        }

        [HttpPost][Authorize(Roles ="Editor, Admin")]
        // sadece Editor ve Admin makale güncelleyebilir.
        public JsonResult ChangeStatus([FromBody] PostChangeStatusInputModel model)
        {
            var post = _postRepository.Find(model.Id);
            post.SetPostStatus(model.IsActive);
            _postRepository.Save();

            return Json(model);
        }

    }
}

NetCoreBlogEntires/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetCoreBlogEntires.Data.Models;
using NetCoreBlogEntires.Data.Repositories;
using NetCoreBlogEntires.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace NetCoreBlogEntires.Controllers
{
    public class PostController : Controller
    {

        private readonly IPostRepository _postRepository;


        public PostController(IPostRepository postRepository)
        {
            _postRepository = postRepository;
        }

        public IActionResult List(string searchText, string categoryId, string tagName, int currentPage = 1)
        {

            // sayfada ne kadar filtereleme varsa bu filtreler querystring üzerinden yakalanıp, viewbag olarak sayfaya geri gönderilir. ve sayfalama butonu bu son filtre değerlerine göre düzgün sayfalama yapabilir.

            ViewBag.CurrentPage = currentPage;
            ViewBag.SearchText = searchText;
            ViewBag.TagName = tagName;
            ViewBag.CategoryId = categoryId;


      

            Expression<Func<Post, bool>> queryFilter = x => x.IsActive;
          

            if (!string.IsNullOrEmpty(searchText))
            {
                queryFilter = x => EF.Functions.Like(x.Title, $"%{searchText}%") || EF.Functions.Like(x.ShortContent, $"%{searchText}%") && x.IsActive;
            }

            if(!string.IsNullOrEmpty(categoryId))
            {
                queryFilter = x => x.CategoryId == categoryId && x.IsActive;
            }

            if(!string.IsNullOrEmpty(tagName))
            {
                queryFilter = x => x.Tags.Select(a=> a.Name).Contains(tagName) && x.IsActive;
            }



            var model = new PostListViewModel
            {

                PostItems = _postRepository.GetPagedPosts(queryFilter, currentPage,4).Select(a => new PostItemViewModel
                {
                    AuthorName = a.AuthorName,
                    CategoryId = a.CategoryId,
                    CategoryName = a.Category.Name,
                    CommentCount = a.Comments.Count(),
                    Tags = a.Tags.Select(a => a.Name).ToArray(),
                    Id = a.Id,
                    PublishDate = a.PublishDate.ToShortDateString(),
                    ShortContent = a.ShortContent,
                    Title = a.Title
   
                }).ToList(),
                PageCount = _postRepository.GetTotalPageNumber(queryFilter,4)

            };


            return View(model);
        }


        public IActionResult Detail(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }


           var post =  _postRepository.Find(id);

            var model = new PostDetailViewModel
            {
                CategoryName = post.Category.Name,
                AuthorName = post.AuthorName,
                Content = post.Content,
                PostId = post.Id,
                PublishDate = post.PublishDate.ToShortDateString(),
                TagNames = post.Tags.Select(x => x.Name).ToArray(),
                Title = post.Title

            };

            // EF çekilen sorguya göre post üzerinden comment bilgisini ramde tutuğundan dolayı aşağıdaki sorgunun çalışmasından sonra comment sayısı değişecektir. yukarıdaki var post nesnesinin referansı değieceğei için ekranda 5 adet comment ile tüm comment sayılarını doğru bir şekilde göstermek için sıralı bir şekilde işlem yapmamız gerekti.
            model.Comments = post.Comments.Select(a => new CommentViewModel
            {
                CommentBy = a.CommentBy,
                PublishDate = a.PublishDate.ToShortDateString(),
                Text = a.Text
            }).ToList();

            model.CommentCount = _postRepository.GetTotalCommentsCount(id);

            


          

            return View(model);

        }


        [HttpPost]
        public JsonResult SendComment([FromBody] PostCommentInputModel model)
        {


            var post = _postRepository.Find(model.PostId);
            var comment = new Comment(commentBy: model.CommentBy, text: model.Text);
            post.AddComment(comment);
            _postRepository.Save();

            model.PublishDate = comment.PublishDate.ToShortDateString();

            return Json(model);
        }
    }
}

NetCoreBlogEntires/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreBlogEntires.Data.Repositories;
using NetCoreBlogEntires.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreBlogEntires.ViewComponents
{
    public class CategoryListViewComponent: ViewComponent
    {


        private readonly ICategoryRepository _categoryRepository;

        public CategoryListViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {

            var model = _categoryRepository
                .List()
                .Select(a=> new CategoryViewModel { 
            
                Id = a.Id,
                CategoryName = a.Name
            })
                .ToList();


            return View(await Task.FromResult(model));

        }
    }
}

NetCoreBlogEntires/ViewComponents/PostItemViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreBlogEntires.Data.Repositories;
using NetCoreBlogEntires.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreBlogEntires.ViewComponents
{
    public class PostItemViewComponent: ViewComponent
    {
 
        public async Task<IViewComponentResult> InvokeAsync(PostItemViewModel model)
        {

            return View(await Task.FromResult(model));

        }

        
    }
}

NetCoreBlogEntires/ViewComponents/RecentPostListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreBlogEntires.Data.Repositories;
using NetCoreBlogEntires.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreBlogEntires.ViewComponents
{
    public class RecentPostListViewComponent: ViewComponent
    {

        private readonly IPostRepository _postRepository;

        public RecentPostListViewComponent(IPostRepository postRepository)
        {
            _postRepository = postRepository;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {

            var model = _postRepository
                .Where(x=> x.IsActive)
                 .OrderByDescending(x=> x.PublishDate)
                 .Take(3)
                .Select(a => new RecentPostViewModel
                {

                    PostId = a.Id,
                    Title = a.Title,
                    PublishDate = a.PublishDate.ToShortDateString()
                })
                .ToList();


            return View(await Task.FromResult(model));

        }
    }
}

NetCoreBlogEntires/ViewComponents/TagListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreBlogEntires.Data.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreBlogEntires.ViewComponents
{
    public class TagListViewComponent: ViewComponent
    {
        private readonly ITagRepository _tagRepository;

        public TagListViewComponent(ITagRepository tagRepository)
        {
            _tagRepository = tagRepository;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {

            var model = _tagRepository.List().Select(a => a.Name).ToList();


            return View(await Task.FromResult(model));

        }
    }
}

NetCoreBlogEntires/Views/Post/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model PostDetailViewModel




<section class="blog-posts grid-system">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="assets/images/blog-post-02.jpg" alt="">
                                </div>
                                <div class="down-content">
                                    <span>@Model.CategoryName</span>
                                    <a href="post-details.html"><h4>@Model.Title</h4></a>
                                    <ul class="post-info">
                                        <li><a href="#">@Model.AuthorName</a></li>
                                        <li><a href="#">@Model.PublishDate</a></li>
                                        <li><a href="#" ><span class="commentCount">@Model.CommentCount</span> <span>Comments</span></a></li>
                                    </ul>
                                    <p>
                                        @Html.Raw(Model.Content)
                                    </p>
                                    <post-tag-list tag-names="@Model.TagNames"></post-tag-list>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item comments">
                                <div class="sidebar-heading">
                                    <h2><span class="commentCount">@Model.CommentCount </span> <span>Comments</span></h2>
                                </div>
                                <div class="content">
                                    <ul style="display: flex; flex-direction: column;" id="commentContainer">

                                        @foreach (var comment in Model.Comments)
                                        {

                                            <li>
                                                <div class="author-thumb">
                                                    <img src="/site/assets/images/comment-author-01.jpg" alt="">
                                                </div>
                                                <div class="right-content">
                                                    <h4>@comment.CommentBy<span>@comment.PublishDate</span></h4>
                                                    <p>@comment.Text</p>
                                                </div>
                                            </li>
                                        }


                                    </ul>
                                </div>
                            </div>
                        </div>


                        @* Yorum yazma formu *@

                        <div class="col-lg-12">
                            <div class="sidebar-item submit-comment">
                                <div class="sidebar-heading">
                                    <h2>Your comment</h2>
                                </div>
                                <div class="content">
                                    <form id="comment" name="commentForm" method="post" onsubmit="FormSubmit(event)">
                                        <input id="postId" type="hidden" name="PostId" value="@Model.PostId" />
                                        <div class="row">
                                            <div class="col-md-6 col-sm-12">
                                                <fieldset>
                                                    <input name="CommentBy"  type="text" id="name" placeholder="Your name" >
                                                </fieldset>
                                            </div>
                                        
                                            <div class="col-lg-12">
                                                <fieldset>
                                                    <textarea name="Text" rows="6" id="message" placeholder="Type your comment" ></textarea>
                                                </fieldset>
                                            </div>
                                            <div class="col-lg-12">
                                                <fieldset>
                                                    <button type="submit" id="form-submit" class="main-button">Yorum Yap</button>
                                                </fieldset>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form method="GET" action="/Post/List">
                                    <input type="text" name="searchText" class="searchText" placeholder="type to search..." autocomplete="on">
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            @await Component.InvokeAsync("RecentPostList")
                        </div>
                        <div class="col-lg-12">
                            @await Component.InvokeAsync("CategoryList")
                        </div>
                        <div class="col-lg-12">

                            @await Component.InvokeAsync("TagList")

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


@section Scripts {

    <script>

        $(document).ready(function () {
            $('img').css('max-width','40rem');
        });

    const FormSubmit = (event) => {
        event.preventDefault();

        console.log('event', event);

        const param = {
           /* PostId: $('#postId').value(),*/
             PostId: commentForm.PostId.value,
            CommentBy: commentForm.CommentBy.value,
            Text: commentForm.Text.value
        }

        console.log('comment', param);


        $.ajax({
            method: 'post',
            url: '/Post/SendComment',
            data: JSON.stringify(param),
            contentType: 'application/json',
            success: function (response) {

                // prepend ilgili elementin en başına ekler.
                // append sonuna ekler.
                $("#commentContainer").prepend(`<li><div class="author-thumb"><img src="/site/assets/images/comment-author-01.jpg" alt=""></div><div class="right-content"><h4>${response.commentBy === "" ? 'Anonim Hesap' : response.commentBy}<span> ${response.publishDate}</span></h4><p>${response.text}</p></div></li>`)

                let commentCount = Number($('.commentCount:first').text());


                console.log('comment-count', commentCount);
                $('.commentCount').text(++commentCount);


                swal("Başarı!", "Yorumunuz eklenmiştir!", "success");

                commentForm.CommentBy.value = "";
                commentForm.Text.value = "";

                // comment sayımızda 1 adet artırdık
                // comment sayısını artırıcaz
                // comment append et.
            },
            error: function (err) {

                swal("Hata!", "Yorum alanı boş geçilemez!", "error");
            /*    console.log('hata', err);*/
            }
        })

        }


        // https://sweetalert.js.org/guides/



    </script>

}

NetCoreBlogEntires/Views/Post/List.cshtml
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model PostListViewModel



<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">


                    <div class="row">

                        @foreach (var item in Model.PostItems)
                        {

                            @await Component.InvokeAsync("PostItem", item)

                        }



                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form method="GET" action="/Post/List">
                                    <input type="text" name="searchText" class="searchText" placeholder="type to search..." autocomplete="on">
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            @await Component.InvokeAsync("RecentPostList")
                        </div>
                        <div class="col-lg-12">
                            @await Component.InvokeAsync("CategoryList")
                        </div>
                        <div class="col-lg-12">

                            @await Component.InvokeAsync("TagList")

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-12">
            <ul class="page-numbers">

                @for (int i = 1; i <= Model.PageCount; i++)
                {
                    @if (i == ViewBag.CurrentPage)
                    {
                        <li  class="active"><a asp-controller="Post" asp-action="List" asp-route-currentPage="@i">@i</a></li>

                    }
                    else
                    {
                        <li><a asp-controller="Post" asp-action="List" asp-route-currentPage="@i" asp-route-searchText="@ViewBag.SearchText" asp-route-tagName="@ViewBag.TagName" asp-route-categoryId="@ViewBag.CategoryId">@i</a></li>
                    }

                }

            </ul>
        </div>
    </div>
</section>